export const ERROR_CODES = {
  validationError: 'VALIDATION_ERROR',
  unauthorized: 'UNAUTHORIZED',
  forbidden: 'FORBIDDEN',
  notFound: 'NOT_FOUND',
  internalError: 'INTERNAL_ERROR',
  unknownError: 'UNKNOWN_ERROR',
  invalidCredentials: 'INVALID_CREDENTIALS',
  invalidRefreshToken: 'INVALID_REFRESH_TOKEN',
  duplicateStudent: 'DUPLICATE_STUDENT',
  duplicateBusOwner: 'DUPLICATE_BUS_OWNER',
  duplicateBus: 'DUPLICATE_BUS',
  duplicateDriver: 'DUPLICATE_DRIVER',
  invalidDateRange: 'INVALID_DATE_RANGE',
  driverForbidden: 'DRIVER_FORBIDDEN',
  busForbidden: 'BUS_FORBIDDEN',
  assignmentOverlap: 'ASSIGNMENT_OVERLAP',
  noActiveBusAssignment: 'NO_ACTIVE_BUS_ASSIGNMENT',
  qrNotFound: 'QR_NOT_FOUND',
  nonWorkingDay: 'NON_WORKING_DAY',
  dailyBoardingLimitReached: 'DAILY_BOARDING_LIMIT_REACHED',
  rateLimitExceeded: 'RATE_LIMIT_EXCEEDED',
  scanRateLimitExceeded: 'SCAN_RATE_LIMIT_EXCEEDED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
